language: python
python:
  - "2.6"
  - "2.7"
install: pip install . --use-mirrors
script: nosetests
notifications:
  email:
    recipients:
      - turtlebender@gmail.com
    on_success: change
    on_failure: always
